# Generated by Django 5.2.13 on 2026-04-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id_topic', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('is_complete', models.BooleanField()),
                ('priority', models.IntegerField()),
                ('id_exam', models.ForeignKey(db_column='id_exam', on_delete=django.db.models.deletion.DO_NOTHING, to='exams.exam')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'Topic',
            },
        ),
    ]
