# Generated by Django 5.2.14 on 2026-05-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id_exam',
            field=models.ForeignKey(db_column='id_exam', on_delete=django.db.models.deletion.DO_NOTHING, related_name='topics', to='exams.exam'),
        ),
    ]
