# Generated by Django 5.2.14 on 2026-05-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_priority_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSubtopic',
            fields=[
                ('id_subtopic', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('id_topic', models.ForeignKey(db_column='id_topic', on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Topic Subtopic',
                'verbose_name_plural': 'Topic Subtopics',
                'db_table': 'TopicSubtopic',
            },
        ),
    ]
