# Generated by Django 5.2.14 on 2026-05-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('topics', '0005_topicsubtopic_plan_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicsubtopic',
            options={'ordering': ['sort_order', 'id_subtopic'], 'verbose_name': 'Topic Subtopic', 'verbose_name_plural': 'Topic Subtopics'},
        ),
        migrations.AlterField(
            model_name='topic',
            name='id_exam',
            field=models.ForeignKey(db_column='id_exam', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='exams.exam'),
        ),
    ]
