# Generated by Django 5.2.13 on 2026-04-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('duration_minutes', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('id_topic', models.ForeignKey(db_column='id_topic', on_delete=django.db.models.deletion.DO_NOTHING, to='topics.topic')),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'db_table': 'StudySession',
            },
        ),
    ]
