# Generated by Django 5.2.13 on 2026-04-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('planned_date', models.DateField()),
                ('repetition_number', models.IntegerField()),
                ('is_done', models.BooleanField(blank=True, null=True)),
                ('id_topic', models.ForeignKey(db_column='id_topic', on_delete=django.db.models.deletion.DO_NOTHING, to='topics.topic')),
            ],
            options={
                'verbose_name': 'Study Plan',
                'verbose_name_plural': 'Study Plans',
                'db_table': 'StudyPlan',
            },
        ),
    ]
