PRIORITY_HIGH = 'высокий'
PRIORITY_MEDIUM = 'средний'
PRIORITY_LOW = 'низкий'

PRIORITY_CHOICES = (
    (PRIORITY_HIGH, 'Высокий'),
    (PRIORITY_MEDIUM, 'Средний'),
    (PRIORITY_LOW, 'Низкий'),
)

PRIORITY_ORDER = {
    PRIORITY_HIGH: 0,
    PRIORITY_MEDIUM: 1,
    PRIORITY_LOW: 2,
}

VALID_PRIORITIES = {PRIORITY_HIGH, PRIORITY_MEDIUM, PRIORITY_LOW}
