# Generated by Django 5.2.13 on 2026-04-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id_daily', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('done', models.BooleanField()),
                ('id_topic', models.ForeignKey(db_column='id_topic', on_delete=django.db.models.deletion.DO_NOTHING, to='topics.topic')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'verbose_name': 'Daily Task',
                'verbose_name_plural': 'Daily Tasks',
                'db_table': 'DailyTask',
            },
        ),
    ]
